[[plugins]]
repo = 'Shougo/unite.vim'
hook_add = '''
    nmap <Space> [unite]
    nnoremap <silent> [unite]f :<C-u>Unite<Space>file<CR>
    nnoremap <silent> [unite]m :<C-u>Unite<Space>buffer file_mru<CR>
    nnoremap <silent> [unite]d :<C-u>Unite<Space>directory_mru<CR>
    nnoremap <silent> [unite]b :<C-u>Unite<Space>buffer<CR>
    nnoremap <silent> [unite]r :<C-u>Unite<Space>register<CR>
    nnoremap <silent> [unite]t :<C-u>Unite<Space>tab<CR>
    nnoremap <silent> [unite]h :<C-u>Unite<Space>history/yank<CR>
    nnoremap <silent> [unite]o :<C-u>Unite<Space>outline<CR>
    nnoremap <silent> [unite]v :<C-u>Unite<Space>bookmark<CR>
'''

[[plugins]]
repo = 'Shougo/neomru.vim'
on_source = ['unite.vim']

[[plugins]]
repo = 'Shougo/unite-outline'
on_source = ['unite.vim']

[[plugins]]
repo = "rking/ag.vim"
on_source = ['unite.vim']
hook_add = '''
    nnoremap <silent> [unite]g  :<C-u>Unite grep:. -buffer-name=search-buffer<CR>
    nnoremap <silent> [unite]r  :<C-u>UniteResume search-buffer<CR>
    if executable('ag')
        let g:unite_source_grep_command = 'ag'
        let g:unite_source_grep_default_opts = '--nogroup --nocolor --column'
        let g:unite_source_grep_recursive_opt = ''
    endif
'''
